vmiklos/plees-tracker

- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_sleep.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
> Add dark mode support.

- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
Fixes <https://github.com/vmiklos/plees-tracker/issues/1>.
> Fix file import if android uses another mimeType for csv

- app/src/main/res/values-es/strings.xml
Per #30, I translate new string for 7.0.1 version.
> New spanish translation

- app/build.gradle
Change-Id: I89a1e0d0e29dd23f01be1c2e656ab09502252278
> Update androidx.core:core-ktx to 1.3.2

- app/build.gradle
Change-Id: Ibb3cac6c521aa033578824650d8d00c7e842fec5
> Update com.google.android.material:material to 1.2.1

- NEWS.adoc
- build.gradle
Change-Id: I773868c41c2480d0cd33fb71c1ba9f6d75da7a83
> Update com.android.tools.build:gradle to 4.0.2

- app/src/main/java/hu/vmiklos/plees_tracker/calendar/UserEvent.kt
Change-Id: I3ef6b9828df449828606567c4055ab79aa79c4e3
> Fix style issues in UserEvent

- HACKING.adoc
- app/src/main/java/hu/vmiklos/plees_tracker/calendar/UserCalendar.kt
Change-Id: I0db23c71196f508fcdb4ed72ff144b55dd319c17
> Fix style issues in UserCalendar

- app/build.gradle
Change-Id: I0f166ba12aaf1d3c946f3e27e325b1259d0d2e8d
> Update androidx.constraintlayout:constraintlayout to 2.0.2

- app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityInstrumentedTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
- app/src/main/java/hu/vmiklos/plees_tracker/MainViewModel.kt
- app/src/main/java/hu/vmiklos/plees_tracker/calendar/CalendarExport.kt
- app/src/main/java/hu/vmiklos/plees_tracker/calendar/CalendarImport.kt
- app/src/main/java/hu/vmiklos/plees_tracker/calendar/CursorExt.kt
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values/strings.xml
Change-Id: I9f6b6996f41552fc1d7b7985f20dabba58e4d5fd
> Adds export to calendar functionality. Fixes #41

- NEWS.adoc
- app/src/main/java/hu/vmiklos/plees_tracker/calendar/CalendarExport.kt
Needless blank line and long line. Also update NEWS.
Change-Id: I1ceff3e07be4245359e62d9292bc03a32d6eab3d
> CalendarExport: fix some style nits

- .idea/compiler.xml
- .idea/gradle.xml
- .idea/jarRepositories.xml
- .idea/misc.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Change-Id: I9cf92ba4f96d5a7d4a65752f71babb37263c0dad
> Update to Android Studio 4.1

- app/src/main/java/hu/vmiklos/plees_tracker/calendar/CalendarImport.kt
Change-Id: I620fe772665326a345fa04fde16f04b2c0bc83d3
> CalendarImport: wrap long lines, other whitespace fixes

- app/src/test/java/hu/vmiklos/plees_tracker/DataModelUnitTest.kt
Change-Id: I52dbf46ac9083d10b7cfa9192acebde9da6322c8
> DataModelUnitTest: fix whitespace problems

- app/src/main/java/hu/vmiklos/plees_tracker/StatsActivity.kt
Change-Id: I15bd14a60ba45f9467f37f510fdced7f18e644ad
> StatsActivity: fix whitespace problems

- app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt
Change-Id: I1dc24270d942467b796eaf4197fda23676353e82
> SleepViewModel: fix whitespace problems

- app/src/main/java/hu/vmiklos/plees_tracker/SleepsAdapter.kt
Change-Id: I2ee35535c3f23dfdae358b72399920416e385896
> SleepsAdapter: fix whitespace problems

- build.gradle
Change-Id: I89fe7e1efa9a9aa0e7d4b037b38aece82b22b298
> Update com.android.tools.build:gradle to 4.1.1

- README.adoc
Change-Id: I078db1eed286c9178a91adb8b34a4a6e13eb4389
> Update CI badge to github actions

- app/src/main/java/hu/vmiklos/plees_tracker/PreferencesActivity.kt
Change-Id: I12bc27ccc0121e4fc9a7bee085d95c168358e64f
> Fix whitespace in PreferencesActivity

- app/src/main/java/hu/vmiklos/plees_tracker/MainService.kt
Change-Id: I8630c42a0950dc722100f98d17ea6be06f5e0155
> Fix whitespace in MainService

- app/src/main/java/hu/vmiklos/plees_tracker/MainViewModel.kt
Change-Id: I82959459403d7973b564279be036307650e1097e
> Fix whitespace in MainViewModel

- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
Change-Id: I5c0b0dc7854ae6cccb20d699f0bb70b258987cd6
> Fix whitespace in MainActivity

- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
Change-Id: I891b845a4e07f422eaf3a37dbf0c49c5c558512c
> Fix whitespace in DataModel

- app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityInstrumentedTest.kt
Change-Id: I5449368490e2abecab073879fb75259a5e7237e5
> Fix whitespace in MainActivityInstrumentedTest

- NEWS.adoc
- README.adoc
- app/build.gradle
Change-Id: I11b645e61a56087af7cdeb203d343a70e9e87c76
> plees-tracker 7.0.4

- app/build.gradle
Change-Id: Ia98e00576a96c585d24911483e71d67e597455e1
> androidx.constraintlayout: update constraintlayout to 2.0.4

- build.gradle
Change-Id: I522d29e5ee33d67544a251680b4488e912cb96f4
> Update kotlin version in gradle to match the IDE version

- app/build.gradle
Change-Id: Idc419df64ca9112c38ac5f44526f0a84f13f3f00
> Migrate away from deprecated kotlin-android-extensions

- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
- app/src/main/java/hu/vmiklos/plees_tracker/PreferencesActivity.kt
Change-Id: I209f0f3017817a9e65b35cf44f71ef8c88d348d3
> Remove redundant public modifiers

- app/src/main/java/hu/vmiklos/plees_tracker/SharedPreferencesChangeListener.kt
Change-Id: Ib7cf9bd57804d6c403fd8978fe547d0deac81553
> Remove empty primary constructor

- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
Change-Id: I34a72c8e9d0f7bb60855605d44327cf80497988e
> Fold if-null return/break to ?:

- HACKING.adoc
- build.gradle
Change-Id: I4aec2c9b026b9cf8507bcb4850c8dc935ac82802
> Update kotlin to 1.4.21

- app/src/main/res/values-pt-rBR/strings.xml
https://github.com/vmiklos/plees-tracker/discussions/84#discussioncomment-246610
> Update pt-br translation for 7.0.5 release

- NEWS.adoc
- README.adoc
- app/build.gradle
Change-Id: I38531ae48c7e6e30667057f224c0ba42b46baf55
> plees-tracker 7.0.5

- app/build.gradle
Change-Id: Ie2265c67b95b8ed06d391972986a31536d92bb77
> Update room to 2.2.6

- build.gradle
Change-Id: I51f9e925c60079e201d3df0aac8f8ac1efd3e350
> Update com.android.tools.build:gradle to 4.1.2

- .github/workflows/tests.yml
- tools/ci-build.sh
Change-Id: Ic062674c79e12d7e7a187e5c71360253601b68c2
> CI: auto-upload a debug APK for each release

- .github/workflows/tests.yml
Change-Id: I6137d09a80c6e93fc1a9e19fa2993411b37ec896
> CI: trigger on creating tags

- app/src/main/res/values-pt-rBR/strings.xml
https://github.com/vmiklos/plees-tracker/discussions/101
> Update pt-br translation for 7.1.0 release

- NEWS.adoc
- README.adoc
- app/build.gradle
Change-Id: I18c07ff4bdbd3e38f3746273ae890cf66ab7b888
> plees-tracker 7.1.0

- app/src/main/java/hu/vmiklos/plees_tracker/SleepsAdapter.kt
Change-Id: Ia91e4e748aee8f7ecadbb9ae03641f0f00232d0a
> SleepsAdapter: remove not needed semicolon

- app/src/main/java/hu/vmiklos/plees_tracker/SharedPreferencesLiveData.kt
Change-Id: I5bf98d1107c20394a390c4a10853e8080bef5ed0
> Clean up unused SharedPreferencesLiveData functions

- app/build.gradle
Change-Id: Id14cd31cd3f15a0d3b087528f2b59dc515bcb44a
> Update androidx.activity:activity-ktx to 1.2.0

- app/build.gradle
Change-Id: I384a3c032797b02a21a2dc62c2b8b203c202b747
> Update com.google.android.material:material to 1.3.0

- app/build.gradle
Change-Id: Iee7386c23cac2a5c522cc5851e183fc6ac075dd7
> Update androidx.lifecycle:lifecycle-viewmodel-ktx to 2.3.0

- app/src/main/java/hu/vmiklos/plees_tracker/ToggleWidget.kt
Change-Id: I5d5ba576b90c26148664440a6b6807d77851822e
> ToggleWidget: eliminate non-null-assertion operators

- app/src/test/java/hu/vmiklos/plees_tracker/GraphsActivityUnitTest.kt
- tools/ci-build.sh
- tools/license-check.sh
And a script to check for these during CI.
Change-Id: Ib8ebf7494fbd0274a345f15ca860d7f9e33f2eaf
> Add missing license header

- .idea/jarRepositories.xml
- app/src/main/java/hu/vmiklos/plees_tracker/Sleep.kt
Change-Id: Ic82bf63f02ee81182fc3bf522ec344dab6af45b9
> Sleep: lengthMs can be private

- NEWS.adoc
- README.adoc
- app/build.gradle
Change-Id: Ieb817851a6db90b6cdfdddc0c148e0efd3307871
> plees-tracker 7.1.1

- app/build.gradle
Change-Id: I300004c897715b9b1102188eea925b04735b70f9
> gradle: update androidx.activity:activity-ktx to 1.2.1

- build.gradle
Change-Id: I01aa309da978017d5b3c3c461646ab61d3385c68
> gradle: update androidx.fragment:fragment-ktx to 1.3.1

- NEWS.adoc
- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SleepsAdapter.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
- doc/README.adoc
Change-Id: I74cc7a22cb5f2a5c31bba0771607670951d31cc1
> sleep card: hide awake-for time & rating by default

- app/src/main/res/xml/preferences.xml
- doc/README.adoc
In practice you probably want to maintain a good average for this
duration, the rest is more just interesting stats.
Change-Id: I913bbc1752b50121bd065a45cb7fe33e2abdd157
> Default to 1 week duration in the dashboard

- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
Change-Id: Id3abeba184cb0ad5a450655157c4f939c998cfc4
> Keep config and code detauls in sync

- build.gradle
Change-Id: Ibaf52fd2ac658a05ef60ae0380216432b8a2f073
> gradle: update kotlin to 1.4.32

- app/build.gradle
Change-Id: I7dcd9b4f2264fa10ff6a89e937c43027a66207ba
> Update room to 2.3.0

- app/build.gradle
Change-Id: Ifa0102544d5c1306d3b4fe75df1f7b3a2a1869e6
> gradle: update junit to 4.13.2

- app/build.gradle
Change-Id: I0538dcb3d382af6291d95468ce7e3b125935cc93
> gradle: update androidx.fragment:fragment-ktx to 1.3.3

- app/src/main/java/hu/vmiklos/plees_tracker/calendar/UserCalendar.kt
- app/src/main/java/hu/vmiklos/plees_tracker/calendar/UserEvent.kt
Change-Id: I7c5b9b8d5c9964210ca9627df76c11126a701827
> Convert to primary constructor

- app/src/main/java/hu/vmiklos/plees_tracker/calendar/UserCalendar.kt
- app/src/main/java/hu/vmiklos/plees_tracker/calendar/UserEvent.kt
Change-Id: I620f9ddc0cedc20434d1d1006dd5755d8ce6e0e1
> Join declaration and assignment

- .idea/compiler.xml
- .idea/misc.xml
- .idea/runConfigurations.xml
- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Change-Id: I8ae9735a65ddef6c73ae2884bc33506b40dc7627
> Update com.android.tools.build:gradle to 4.2.0

- .idea/codeStyles/Project.xml
Change-Id: Ia60a2a70e7e302132a5d4e1b60107d196cc909e9
> Try to reduce android studio vs ktlint style conflicts

- .idea/codeStyles/codeStyleConfig.xml
- NEWS.adoc
- README.adoc
- app/build.gradle
Change-Id: If8f2fd56943aa1f9b8031ee7e081de0a67bd630f
> plees-tracker 7.1.3

- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
- app/src/main/java/hu/vmiklos/plees_tracker/MainViewModel.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SleepTouchCallback.kt
Really similar to sleep edit.
Fixes <https://github.com/vmiklos/plees-tracker/issues/138>.
Change-Id: Iec991956ff8fbf7ddea34c95ea4a3885b2e61d63
> sleep delete: handle automatic backup

- build.gradle
Change-Id: If193bf1b80e9b49eafaa6b322b8433673c1c844d
> Update com.android.tools.build:gradle to 4.2.1

- app/build.gradle
Change-Id: I19fbe976ee3ef83f118f581c7379745095123faf
> Update buildToolsVersion to 30.0.3

- build.gradle
Change-Id: I9a6e1553c74f56195a25816a8380de6afbeb2073
> Update to kotlin 1.5.10

- .idea/jarRepositories.xml
- build.gradle
Change-Id: I130c9d143df0cc422897a63d6c448a5bd2ccd39b
> Migrate away from deprecated jcenter

- app/build.gradle
Change-Id: I02a6c82a2894e913475e3e9c522a80531ac01ac3
> Update androidx.appcompat:appcompat to 1.3.0

- NEWS.adoc
- app/build.gradle
Change-Id: Ica80d4ef4402cc9b68bdb3884987ada4229385f2
> Update androidx.core:core-ktx to 1.5.0

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/listings/en-US/full-description.txt
Change-Id: Ia615ba1afc60dc6860ea2655d4ed3c1b164dce0f
> plees-tracker 7.1.4

- app/build.gradle
Change-Id: I7f3aacd51c29bbefafbf2e54bb4d975063309562
> Update androidx.activity:activity-ktx to 1.3.3

- NEWS.adoc
- app/src/main/java/hu/vmiklos/plees_tracker/SleepTouchCallback.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SleepsAdapter.kt
- app/src/main/res/drawable/ic_delete.xml
- app/src/main/res/layout/layout_sleep_item.xml
Fixes <https://github.com/vmiklos/plees-tracker/issues/157>.
Change-Id: I8d222a328320a4b2fb6babc3ad0304ef1b118863
> Hint that swiping the sleep will delete it

- app/src/main/res/layout/layout_sleep_item.xml
Change-Id: Id25e3255f3c12beb68d1c7cf67715a9f5211ae42
> layout_sleep_item: left/right -> start/end

- app/src/main/res/layout/activity_stats.xml
This should fix #162.
<details>
<summary>Video</summary>
</details>
> Fix statistics activity scrolling

- build.gradle
Change-Id: I93c0ec97e9e686c37e1acab5c743d5d7d30be8f2
> Update com.android.tools.build:gradle to 4.2.2

- app/build.gradle
Change-Id: Ia7e768ec4d81490b3d3c3c0a21bafea82c649d5d
> Update androidx.test.ext:junit to 1.1.3

- app/build.gradle
Change-Id: Iac3863fa7700e772bf431368a75cac36cf1c23a3
> Update androidx.core:core-ktx to 1.6.0

- build.gradle
Change-Id: I31bc6d7181cb9d055a9cc71393653c2ca32ecc41
> Update kotlin to 1.5.20

- app/build.gradle
Change-Id: I51d5122437c3ffa5bdbfdc86386b368bf93f7604
> Update androidx.test.espresso:espresso to 3.4.0

- app/build.gradle
Change-Id: I074a716ca9596e30dc4dc300eac5efa75a9294f9
> Update com.google.android.material:material to 1.4.0

- build.gradle
Change-Id: I8b06f74939e537ac4eeaa325b2297f7e4570aaae
> Update kotlin to 1.5.21

- .github/workflows/tests.yml
Change-Id: Iafeb6d606a15d2a389d2ec18b8d878f0e5b44d35
> Update androidx.fragment:fragment-ktx to 1.3.5

- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SleepsAdapter.kt
Change-Id: I5ca7d05192a854f53ff34afc5d82a3b3ea92dece
> SleepsAdapter: remove no longer used property

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/listings/en-US/full-description.txt
Change-Id: I00e26b5c240a7f7fbb21961c13311988a5ac99a5
> plees-tracker 7.2.0

- app/build.gradle
Change-Id: I46cdf84563edaf8e2d9fee3d1b7d4cf205b18da6
> Update androidx.appcompat:appcompat to 1.3.1

- build.gradle
Change-Id: Ie69fba22a8ff7063d5dd83a4cdd23292fa72b2f2
> Update com.android.tools.build:gradle to 7.0.1

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/listings/en-US/full-description.txt
Change-Id: Icf1c5d583e4a372e52630b53a2bf2630f364465e
> plees-tracker 7.2.1

- build.gradle
Change-Id: Ic3e6d239347c82e1a357e2f8f459b3e09c9dab8b
> Update com.android.tools.build:gradle to 7.0.2

- app/build.gradle
Change-Id: If05e7b89d36f5fb0bc0384308a5a8e8b627c357e
> Update androidx.activity:activity-ktx to 1.3.1

- app/src/main/res/values-pt-rBR/strings.xml
https://github.com/vmiklos/plees-tracker/discussions/194
> Update pt-br translation for 7.2.2 release

- app/build.gradle
In preparation of updating androidx.core:core-ktx to 1.7.0.
Change-Id: I7c2d9c9ab7ce26048fadea905ffa51461ee932b7
> Update compileSdkVersion to 31

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/listings/en-US/full-description.txt
Change-Id: I7623ef250b8d63bb88df01b623e1c9434de1836b
> plees-tracker 7.2.3

- app/build.gradle
Change-Id: Ib27adc91eeac63323eb45d66bf8c7b5356f6e3c6
> Update androidx.appcompat:appcompat to 1.4.0

- app/build.gradle
Change-Id: I41d6f69cc7efeeb45dc8cf979ff0df73c251748e
> Update androidx.constraintlayout:constraintlayout to 2.1.2

- app/build.gradle
Change-Id: I8a6689b17876302f4b6358e033cbc3ca29701128
> Update androidx.core:core-ktx to 1.7.0

- app/build.gradle
Change-Id: I8c66c093d236e38da7779c237d7f42ca3dfa4916
> Update androidx.lifecycle:lifecycle-viewmodel-ktx to 2.4.0

- app/build.gradle
Change-Id: I879d13cac0677b89eeca688e18cd5856591c15d4
> Update androidx.activity:activity-ktx to 1.4.0

- app/build.gradle
Change-Id: Ia74224fb32fa80d0a44a5c95a475ff2f3b644233
> Update androidx.fragment:fragment-ktx to 1.4.0

- app/build.gradle
- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
See
<https://stackoverflow.com/questions/67812490/android-studio-usingonclickinxml-warning>.
Change-Id: I9cb0c3101df9ed15908a29e12b40bd94a6a62123
> Fix lint error around the on-click listener setup

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/listings/en-US/full-description.txt
Change-Id: I04475c0db32307e21a93f1522ebd9d80e121afb7
> plees-tracker 7.2.4

- build.gradle
Change-Id: I063148bfd6fc6872a313fba3300a01e46660bc75
> Update com.android.tools.build:gradle to 7.0.4

- build.gradle
Change-Id: I751066865144bf4dbf7559951ee161a6120cc970
> build: update kotlin version to 1.5.32

- app/build.gradle
- build.gradle
Change-Id: Iff6df2d7c90df06b3e5e69beba4a25d2a42a3386
> Update room version to 2.4.0

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/listings/en-US/full-description.txt
Change-Id: I1f407ed63937004375b797e917efe6672d66d3a7
> plees-tracker 7.2.5

- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values/strings.xml
See
<https://stackoverflow.com/questions/41950952/how-to-use-android-quantity-strings-plurals>.
Change-Id: Ic8e0f6d2fb32b2723c36371c1658ed4f3da21238
> Import/export: fix 'item(s)'

- app/src/main/java/hu/vmiklos/plees_tracker/SleepActivity.kt
Change-Id: I0e85b1ed80b34a917d849f10315fc537dae6b21a
> SleepActivity: remove unused @Suppress

- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
This is easy to do and it helps performance a little.
Change-Id: I9132d2635d64a9fadd11b7680894132555ba1a63
> DataModel: convert to set, only then substract()

- app/build.gradle
Change-Id: I230a321d529e040b04f451a5cd0b8953e8afc59f
> Update androidx.appcompat:appcompat to 1.4.1

- app/build.gradle
Change-Id: I3aa6b851967cf314c427e3eade189d20a2d42f67
> Update androidx.constraintlayout:constraintlayout to 2.1.3

- app/src/main/java/hu/vmiklos/plees_tracker/AppDatabase.kt
- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
- app/src/main/java/hu/vmiklos/plees_tracker/Sleep.kt
Related to <https://github.com/vmiklos/plees-tracker/issues/239>.
Change-Id: I1d448e70442436c8a13d015c70affeca6050e934
> Sleep comments: add data model

- app/build.gradle
- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
Otherwise contents after a "," in a note would be lost on import.
Change-Id: I0db66254c991a7542e86003c68184019dd93bfca
> Switch to opencsv for CSV import/export

- app/src/main/res/layout/activity_sleep.xml
- app/src/main/res/values/strings.xml
- doc/README.adoc
Related to <https://github.com/vmiklos/plees-tracker/issues/239>.
Change-Id: Ia707bb502e4ec7d48b4190d376cfdbcdbd8f9ce6
> sleep layout: add a label for the notes edit-text

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Change-Id: I96d7ba5e433092a448c789ee9b2ef856b290684f
> Update gradle to 7.2

- app/build.gradle
- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
Mostly to get rid of the DuplicatePlatformClasses error
Change-Id: I39877ccc460bf24ea779e67f58e4aaee74300602
> Switch to apache commons csv

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/listings/en-US/full-description.txt
Change-Id: Iaa38d565d9af0c77787b433de1f2113f13b5e09a
> plees-tracker 7.3.0

- build.gradle
Change-Id: I184647cfff02241fe234712cc81878583a66ccd1
> Update com.android.tools.build:gradle to 7.1.1

- app/build.gradle
Change-Id: I946686f82411404b473b3adf09aa9ff620310378
> Update room to 2.4.1

- app/build.gradle
Change-Id: Ice03a0fd4ca321dc0154f0f7561b50e523f1c9e0
> Update com.google.android.material:material to 1.5.0

- app/build.gradle
Change-Id: I27609474761f5e086f18b66d0bbc3576b5bf933d
> Update androidx.lifecycle:lifecycle-viewmodel-ktx to 2.4.1

- app/build.gradle
Change-Id: I3b24d2a3c863f882f90bf16d18f562575df60874
> Update androidx.fragment:fragment-ktx to 1.4.1

- build.gradle
Change-Id: I31bd0d1c2f55fa733410ef3097e1745087aee435
> Update com.android.tools.build:gradle to 7.1.2

- NEWS.adoc
- app/src/main/java/hu/vmiklos/plees_tracker/SleepCommentCallback.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SleepRateCallback.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt
Remember what was the last added listener and remove it before adding a
one one.
Change-Id: I17b19bba21fafde640d1bf77911719ae3faff893
> SleepViewModel: fix leaked comment listener

- app/src/main/java/hu/vmiklos/plees_tracker/SleepCommentCallback.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SleepRateCallback.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt
Change-Id: I364ea01de71f9392ec37a883ed19baeeafa7d179
> Remove now unused activity fields from callback classes

- app/src/main/res/layout/activity_main.xml
Change-Id: I37f82e011f015fafc9dd544fe28e0b86b741d15f
> Remove redundant XML namespace

- app/build.gradle
Change-Id: I2a100f54aeea84ea9bcf0e44b365fda754dacfe7
> Update Room to 2.4.2

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/listings/en-US/full-description.txt
Change-Id: I1aaf367f9cc9ce109d45ac401f9d334b26743262
> plees-tracker 7.3.1

- app/src/main/java/hu/vmiklos/plees_tracker/MainViewModel.kt
Change-Id: I60af79e28bd90f59bc987380c77a30b353881c24
> MainViewModel: remove no longer needed insertSleeps()

- .github/workflows/tests.yml
- app/src/main/java/hu/vmiklos/plees_tracker/SleepDao.kt
Change-Id: Ie73ae77791e8038e07cc548d49a8bac083da6656
> SleepDao: remove no longer needed getAfter()

- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SleepsAdapter.kt
These were public only by accident.
Change-Id: Ife76d833fcb2d93df2ef8da9e199623d7867c00f
> Mark all these as private

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/listings/en-US/full-description.txt
Change-Id: I19a60394eae9bceb4dfc58d8d60a6f057121cffc
> plees-tracker 7.3.2

- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
Change-Id: I9b9779f27c13bd902d06e17426cf5776a84eb615
> MainActivity: remove obsolete SDK version check

- build.gradle
Change-Id: Ie8f5dda0153f14fb7c4cc36e9b3eeacccee415a0
> build: update kotlin to 1.6.20

- build.gradle
Change-Id: Ia959d9a6b15fcd0c93f1f5e864fb0d94572d48ce
> build: update com.android.tools.build:gradle to 7.1.3

- build.gradle
Change-Id: Ia7ed3a542a358e06cf9832c6c0f68a887a078054
> build: update kotlin version to 1.6.21

- app/src/main/java/hu/vmiklos/plees_tracker/SleepsAdapter.kt
Change-Id: Ief0653d00d5f58d73fb3a9e9034bddaf342d6ff0
> Use property access syntax instead of setter method

- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
Change-Id: I82d3f8e90f7f9aa762d94db5c653fd2709f7ebc6
> Data model: declare importedSleeps using val as it's never modified

- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
- app/src/main/java/hu/vmiklos/plees_tracker/MainViewModel.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SleepDao.kt
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values/strings.xml
Change-Id: I50be9eae93f2a4b778344ff1427202402de57ad3
> add delete all sleep data

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/listings/en-US/full-description.txt
- release-notes/en-US/default.txt
- Add menu item to delete all sleeps (Ely M)
- Resolves: gh#285 main service: fix crash on Android 12
Change-Id: I6e54640b7b82a566e0198f4045d851e476109292
> plees-tracker 7.3.4

- .idea/gradle.xml
- build.gradle
Change-Id: Iba6dcd14c20ed44df40d835d99f9b34c7383f71c
> build: update com.android.tools.build:gradle to 7.2.1

- app/build.gradle
Change-Id: Ic2cedd5ad56c75bdc8faeed8e500e2b60484ab57
> build: update kotlin to 1.7.0

- app/build.gradle
Change-Id: I56c0b3fdb1d3ac77c1a76fd4b07f30117ff73516
> Update androidx.constraintlayout:constraintlayout to 2.1.4

- NEWS.adoc
- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
- app/src/main/res/values/strings.xml
Unless you have a backup, this is relatively dangerious, better to
confirm before the operation.
Change-Id: Ic5e06ebd8ada0c731005c3a21aa49a6e48828c20
> delete all sleep: confirm before deleting

- app/src/main/java/hu/vmiklos/plees_tracker/GraphsActivity.kt
Change-Id: Icdd392045597eb0ee8e8fed3d7581b68ca7261e7
> graphs activity: move lambda argument out of parentheses

- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
Change-Id: I763a4b18b6068f96da1d6f93723ef689cb2d1b8b
> Move lambda argument out of parentheses

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
Change-Id: Ifc309d07ac410114b256137789dbfbf07c235f8c
> plees-tracker 7.4.0

- app/build.gradle
Change-Id: I165aeed219295b199311ffdecbfe37be55244e8b
> Update room to 2.4.3

- app/build.gradle
Change-Id: I053a1347c0621b3cad6299ccadf77a143c8fca75
> Update com.google.android.material:material to 1.6.1

- app/build.gradle
I.e. Android 12L.
Change-Id: I9f21c7e3b7ef490343ba859b31ef78593a80dedd
> Update compileSdkVersion to 32

- build.gradle
Change-Id: I33115536342e27269c48d1c6eddccf68755a4f5c
> Update com.android.tools.build:gradle to 7.2.2

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
Change-Id: I1fb48362a250f6c887d8aa52448f4330900744e5
> plees-tracker 7.4.1

- app/build.gradle
Change-Id: I8c8093f03526f48291d66ed004df0b8d9f86f58e
> Update androidx.appcompat:appcompat to 1.5.1

- app/build.gradle
androidx.core:core:1.9.0 will require this.
Change-Id: I6bd8513e0bb242cf4a86aac862a8096e693c107d
> Update compileSdkVersion to 33

- app/build.gradle
Change-Id: Ia1c52a77c688aafc7a45b47126de12e2ce911a4a
> Update androidx.core:core-ktx to 1.9.0

- app/build.gradle
Change-Id: Ie7e86865245ec74e715a8043368e0dcb02d354f3
> Update androidx.lifecycle:lifecycle-viewmodel-ktx to 2.5.1

- app/build.gradle
Change-Id: Ic89193f88bed724d297995d893fe5d23b7d1a205
> Update androidx.fragment:fragment-ktx to 1.5.2

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
Change-Id: I54b72d007cb907a2a1933672237b2cd64d800f72
> plees-tracker 7.4.2

- build.gradle
Change-Id: I32b6e701365562a9119d79ce16507dac2046569a
> Update to kotlin 1.7.10

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Change-Id: I947fe98d9b2f6aa1ab2f442156ddbb8624917098
> Update com.android.tools.build:gradle to 7.3.0

- app/build.gradle
Change-Id: I6e82d1140b398f847392150a2448c0c268cf4746
> Update androidx.activity:activity-ktx to 1.6.0

- app/build.gradle
Change-Id: I7f7b5e8c7b20d15975e5d6fc29c9aa946ea492d4
> Update com.google.android.material:material to 1.7.0

- app/build.gradle
Change-Id: I0098bcc7ee13e8c82810dd4161a9b0fd760a990d
> Update androidx.activity:activity-ktx to 1.6.1

- NEWS.adoc
- README.adoc
- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
Change-Id: I02b20e55c52df4be3e588e8b91806394cab3348a
> plees-tracker 7.4.3

- .github/workflows/tests.yml
Change-Id: I54a95326f892a5c929cf06591eb22357c1dd0a52
> CI: update reactivecircus/android-emulator-runner to v2.27.0

- HACKING.md
Towards merging the documentation and the website into a single,
markdown-based guide.
Change-Id: I1cad0c7c80468eff19cc78ce1ed6e25e60a56705
> HACKING: convert this to markdown

- NEWS.md
Towards merging the documentation and the website into a single,
markdown-based guide.
Change-Id: Id64315abe839f397311eec28e8819afd89441e0b
> NEWS: convert this to markdown

- app/build.gradle
Change-Id: I5a5e96162610392de57b21013234305cc93e36db
> Fix running instrumented tests on Android 13

- doc/README.md
Towards merging the documentation and the website into a single,
markdown-based guide.
Change-Id: Ie11991ee396b45835aed5c6c2f7053f372818aba
> doc: convert asciidoc to markdown

- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values/strings.xml
So it's easier to find the user guide.
Change-Id: Ifd0dba714431bb3caea7a9beaf37c86b41d475b4
> menu: rename Website to Documentation

- guide/book.toml
- guide/matomo.js
To be able to see which pages are popular.
Change-Id: I5c204d9c2655ba47fbfafd1653a9744d98d9d359
> guide: add matomo tracking

- app/build.gradle
Change-Id: I98a019cd9cf0c9c6dcf3e672f1839a713cb6e8ea
> Update androidx.test:core to 1.5.0

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: Ifedb1a433a0fe720d8cf791e12a3da8bfc33d070
> plees-tracker 7.4.4

- app/build.gradle
Change-Id: Icd35029313e2a934a1b951d2b4690f4eb70218ea
> Update dependencies (2022-12)

- guide/src/usage.md
Change-Id: I393fc69715d0ca2ba53db810330787db74a5c3f2
> guide: sleep activity: comment is multi-line

- guide/src/SUMMARY.md
- guide/src/contributors.md
Change-Id: I266282202e07c87b8626c69aa576418fd57a50b5
> guide: credit contributors

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: I91d6a05010c80be1ddc07e582477daa0253792f1
> plees-tracker 7.4.5

- app/build.gradle
Change-Id: I2b95523e30a0fab3079334cd3196a3355c48ddbe
> Update dependencies (2023-01)

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: I3d7dc281b266bdb720909bfedddb4d5d61f84a2b
> plees-tracker 7.5.0

- .idea/gradle.xml
- .idea/misc.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Change-Id: I3ab8bd1eb197db25d2da5885a2e3d821e12b4de1
> Update dependencies (2023-02)

- .github/workflows/tests.yml
Change-Id: Ic2556c2c88a99e015632337b81f2764973a8f6b3
> CI: update to macos-12

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: I22739abcc5c37c4e1f7cb2a2080a57190ca59c08
> plees-tracker 7.5.1

- .github/workflows/tests.yml
- app/build.gradle
- app/src/main/java/hu/vmiklos/plees_tracker/MainViewModel.kt
- build.gradle
Change-Id: I62ee8287ec844985ac26ecc881c2d95c24a6e50b
> Update dependencies (2023-03)

- guide/src/news.md
Change-Id: I52567fcf0d3103c5183b10f15f16a8046df61431
> guide: update news.md

- app/build.gradle
- build.gradle
Change-Id: I33e9686f54d08b418cfdded1b7c11f277a3e67c6
> Update dependencies (2023-04)

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: Ia45431a63c3314df4ddf3862c13372850a8357d9
> plees-tracker 7.5.2

- app/src/main/java/hu/vmiklos/plees_tracker/GraphsActivity.kt
- app/src/main/res/menu/menu_graphs.xml
- app/src/main/res/values/strings.xml
Leaving bed in a consistent time is as useful as enterint bed in a
consistent time.
Fixes <https://github.com/vmiklos/plees-tracker/issues/358>.
Change-Id: Ib676ca3fc2a12cc2500d06074e8695404b4bd7e6
> graphs: add a stop time graph

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: Ib3b78f8c100921e33a54e933108076acee39521b
> plees-tracker 7.5.3

- .github/workflows/tests.yml
- .idea/compiler.xml
- .idea/kotlinc.xml
- .idea/misc.xml
- app/build.gradle
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Change-Id: If72346eba0be01e0f47b85216046578ff46e6953
> Update dependencies (2023-05)

- guide/src/README.md
- guide/src/usage.md
Not Plees Tracker or Plees tracker.
Change-Id: I0d8667d523749e4f68b740dcb6de1deece088e31
> guide: settle down on plees-tracker

- guide/src/contributors.md
- guide/src/news.md
Change-Id: I77a579860aeb3290b531e13968d0c8a7fff16061
> guide: update contributors and news

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: I3b55d5a97ae7c90999672ffd502dc3792e9ba5f9
> plees-tracker 7.5.4

- .idea/misc.xml
- app/build.gradle
- build.gradle
Change-Id: If196b192ab7a160885780f85cd8f39f9c67cacd1
> Update dependencies (2023-06)

- app/src/main/res/values-night/colors.xml
- guide/src/news.md
Fixes <https://github.com/vmiklos/plees-tracker/discussions/387>.
Change-Id: Iddcc2fd2854db6c301ce621b6f3daeee743de8e1
> dark mode: improve colots of the start/stop button

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: I4a1d5eb2126b556eb50a8646a050d19a2f48f433
> plees-tracker 7.5.5

- .idea/kotlinc.xml
- app/build.gradle
- build.gradle
Change-Id: I4e1428a53835ff91f5d5141852acdcf7deddbfea
> Update dependencies (2023-07)

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: I5980ef6027145f497c0ff810eadc32396bac087a
> plees-tracker 7.6.0

- .idea/gradle.xml
- .idea/misc.xml
- app/build.gradle
- build.gradle
Change-Id: I239446a232338e31f871dd6a4f507b2731b9f07c
> Update dependencies (2023-08)

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: I93a486006482a3fa47ae84ae493635acbe528ead
> plees-tracker 7.6.1

- build.gradle
Change-Id: Ie4db2d80db0ea005e6c26d927982849ee4c42dd4
> Use 'tasks.register' to avoid unnecessary configuration

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: I049bdd03e1cd209f1a674204e42f4b4a648fbcb4
> plees-tracker 7.6.2

- .idea/kotlinc.xml
- build.gradle
Change-Id: Ibf53fc179f500e00b375e37ede01832dd5619952
> Update dependencies (2023-10)

- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
- app/src/main/java/hu/vmiklos/plees_tracker/SharedPreferencesChangeListener.kt
Change-Id: Idf76176599df9b7d2d2df9bee0123ec99854fffc
> Replace subsequent checks with 'isNullOrEmpty()' call

- app/build.gradle
- app/src/main/java/hu/vmiklos/plees_tracker/SharedPreferencesChangeListener.kt
- app/src/main/java/hu/vmiklos/plees_tracker/TileService.kt
Change-Id: Ic934a0f1594b63a5f8ef9989a33f60f5d92faa04
> Update compileSdk to 34

- app/build.gradle
- app/src/main/play/release-notes/en-US/default.txt
- guide/src/README.md
- guide/src/news.md
Change-Id: Ib1069cf250a957831ff5ca98dfc5ea3a172766b6
> plees-tracker 7.6.3

- app/build.gradle
- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
Change-Id: Idf60b98d5737ba7a0d5a28e24540a5982fdfca47
> Update dependencies (2023-11)

- .idea/kotlinc.xml
- app/build.gradle
- build.gradle
Also update to kotlin 1.9.10, see
<https://stackoverflow.com/questions/77342860/how-to-resolve-the-gradle-build-error-java-lang-nosuchmethoderror>.
Change-Id: Iaf7b8af6f656b0acdc15361ecb2658c24e642f22
> Migrate from kapt to KSP

- app/build.gradle
- app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
- build.gradle
Which requires initializing the database a bit earlier, so that by the
time the view model is created, the database is already there.
> Update dependencies (2024-02)

- app/src/main/java/hu/vmiklos/plees_tracker/Sleep.kt
<https://kt.academy/article/ek-hashcode> suggests doing this.
> Sleep: sync hashCode() with equals()

- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values/strings.xml
as asked in #274 here is PR :-)
> add 30/45/60minutes to "Start time delay" option

- app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
The intention was to have this default to true, preferences.xml had that
default, but not the data model code, fix this.
> Fix the default for compact_view

- app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityUITest.kt
Best to explicitly delete old sleeps than just hoping we won't have any.
> test: clarify on the starting state

- app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityInstrumentedTest.kt
- app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityUITest.kt
And remove an unreliable instrumented test which was disabled already.
> ui test: add delete testcase

- app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityUITest.kt
Also add assert helpers, so actual test code doesn't have to worry about
timeouts, similar to how Cypress does it for web apps.
> uitest: improve test failure message

- app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityUITest.kt
- app/src/androidTest/java/hu/vmiklos/plees_tracker/SleepActivityUITest.kt
- app/src/androidTest/java/hu/vmiklos/plees_tracker/UITestBase.kt
Also add a UITestBase base class to avoid duplication.
> Extract SleepActivityUITest from MainActivityUITest

- app/src/androidTest/java/hu/vmiklos/plees_tracker/SleepActivityUITest.kt
- app/src/androidTest/java/hu/vmiklos/plees_tracker/UITestBase.kt
Turns out no need to go via the UI in this case.
> test: simplify resetDatabase()

- app/src/main/res/values-night/colors.xml
- change background from #000 to #1f1f1f
- change text color from #ffffff to #e0e0e0
- dashboard: customize Sleeps and Daily colors
Fixes <https://github.com/vmiklos/plees-tracker/issues/506>.
> dark mode: reduce contrast of colors

- app/build.gradle
Otherwise our layout looks quite strange, similar to
<https://stackoverflow.com/questions/79210294/unable-to-fix-layout-issue-in-android-sdk-35>.
> SDK 35: avoid edge-to-edge enforcement

- app/build.gradle
- app/src/main/res/values-v35/styles.xml
Otherwise our layout looks quite strange, similar to
<https://stackoverflow.com/questions/79210294/unable-to-fix-layout-issue-in-android-sdk-35>.
> Use SDK 35 & avoid edge-to-edge enforcement
