vmiklos/plees-tracker

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/SleepDao.kt
I ran all provided tests and they succeeded, but i assume that there weren't any tests checking for anything related anyway.
The `sid` is still used and displayed in the ActionBar of the "Sleep Details" pages, and i'm not sure how to go about this one since i don't have any use cases for it on my mind so i don't know who might be affected by this.
If anything, changing the behavior any further seems like taking away existing information about the order in which sleep entries were added.
This fixes #20
=> Sort sleep entries on screen by start date

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt
Act according to the active locale or explicit user preference set in the android system settings.
Even though i very much like the idea of abolishing the 12h format completely, some people might beg to differ. Since there is a user settable preference in the android system anyway, it should be the least intrusive solution to honor these settings.
Improves upon <https://github.com/vmiklos/plees-tracker/issues/19>.
=> Sleep edit: use 24 hours view in the time picker according to system settings

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainViewModel.kt
I carefully tried to do streaming parsing to avoid OOM. But that means
the main activity's recycler view is updated after each & every view. I
don't have exact numbers, but the time for ~300 sleep goes from ~forever
to ~instant.
Change-Id: I388cbaa1189bbea7627674bb04fca7d460c3466d
=> Speed up mass-import of sleeps

app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
Change-Id: I420e88a3cd50dd4def13cbd0cc34ae87fd6e85cc
=> DataModel: use val because sleeps is never re-assigned

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/MainService.kt
To be consistent with the clock app where the stopwatch/timer doesn't
vibrate, either.
See
<https://stackoverflow.com/questions/48261118/cannot-disable-notification-vibration-in-android-8/52207215#52207215>,
sadly need to uninstall the app to have this working (but that doesn't
remove the app data).
Change-Id: If6de618a90bbe48bb0f4f7396be436aa9f701dc0
=> Avoid vibration when the sleep notification is created

.idea/gradle.xml, NEWS.adoc, app/build.gradle, app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainViewModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/PreferencesActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/SharedPreferencesChangeListener.kt, app/src/main/res/values-es/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
The setting is off by default.
Once it's on, the user can choose a folder. The backup.csv in that
folder is updated each time a sleep is stopped. Keep it simple like like
for now, we could later limit this to "once a week", if it's needed.
Fixes <https://github.com/vmiklos/plees-tracker/issues/32>.
Change-Id: I341b3ce1dbdf29b4c4a73b8f4015fda4b1d132e5
=> Add a setting to create automatic exports for backups

app/src/main/java/hu/vmiklos/plees_tracker/PreferencesActivity.kt
We are reading when we check if the backup is already there.
Change-Id: Ic22c6fdf6060236495e74c57babcb34c42ceeafd
=> backup: take RW permission, not just W

contrib/sleep-as-android.py
As suggested in https://github.com/vmiklos/plees-tracker/issues/88. 
Differences from [gist](https://gist.github.com/usashiki/d6f918b1d3c8035f3da8a9f51962c417):
- Changed filename from `convert.py` to `sleep-as-android.py`.
- Added example usage.
=> Add script to convert Sleep as Android CSV

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/Preferences.kt, app/src/main/java/hu/vmiklos/plees_tracker/PreferencesActivity.kt, app/src/main/res/values-es/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
And show the value of the backup path. Add explicit code to update it
not only when the settings activity is restarted, but also when
auto-backup is enabled.
Fixes <https://github.com/vmiklos/plees-tracker/issues/90>.
Change-Id: Ib4ac8d3e4402c8eb9d54d1c38fdfdcba99bc17dc
=> PreferencesActivity: disable autobackup bool when path is empty

tools/ci-build.sh
Which are less interesting.
Change-Id: I64fbbbc89b286b2eaddc6b8f5969bd76d33eeedc
=> CI: deliver just the release apk, not the other two apks

app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepsAdapter.kt, app/src/main/res/layout/layout_sleep_item.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values/strings.xml
Implemented this a while ago for myself and i find it pretty useful.
As this grows each sleep entry even more it might be time to add a preference to toggle each row as desired. At least i personally don't use the rating bar and tweaked it out of the UI in my personal build to get more space.
Currently in this PR:
Re: Tests - I have no experience in this area and don't feel confident to write tests for this, especially if i try to imagine how one would assert values that are supposed to change with second-precision.
=> Feat sleep time

NEWS.adoc, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/ToggleWidget.kt, app/src/main/res/layout/widget_layout_toggle.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/widget_info_toggle.xml
Given that this is something the user does twice a day, it makes sense
to have a single-tap action for this, instead of the two-taps to start
the main activity + press the start/stop button.
Fixes <https://github.com/vmiklos/plees-tracker/issues/92>.
Change-Id: I7acd4d1116210050beee1f4553075883fb544161
=> Add a widget to immediately start/stop tracking

tools/ci-build.sh
In case git-hooks/pre-commit was not enabled locally.
Change-Id: I7f7674aecdc6d53bbfc0343322b46c8f344e05d5
=> CI: require passing ktlint

app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainViewModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/SharedPreferencesLiveData.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepDao.kt, app/src/main/java/hu/vmiklos/plees_tracker/StatsActivity.kt, app/src/main/res/layout/activity_stats.xml, app/src/main/res/layout/fragment_stats.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, doc/README.adoc
Adds a new setting to customize the dashboard duration, which filters
the sleeps visible on the dashboard to the selected duration as well as
the statistics.
Fixes <#88>.
=> Add dashboard duration setting

app/src/main/java/hu/vmiklos/plees_tracker/calendar/UserCalendar.kt, app/src/main/java/hu/vmiklos/plees_tracker/calendar/UserEvent.kt
Both classes have other constructors, just this one is not used.
Change-Id: I3053ce5214a7a87a981e16b63229c06189e4c4a1
=> Remove unused constructors

NEWS.adoc, app/src/main/AndroidManifest.xml, app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/TileService.kt, doc/README.adoc
I'm not exactly sure how to do DB operations without view models, so
just do it the same way as the widget: open the activity with a relevant
flag and then let it do its work.
Fixes <https://github.com/vmiklos/plees-tracker/issues/94>.
Change-Id: If1fe55aee5c2e77f2e4aa4b5845c755365e19176
=> Add a simple quick settings tile

app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainViewModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt
Backup file should get updated after editing as well, fix this by moving
the logic to DataModel and then using this from the Main and from the
Sleep activities.
Related to <https://github.com/vmiklos/plees-tracker/issues/138>.
Change-Id: I38fd9c2bcc6567fbb005c5b0622d821dc633f980
=> edit sleep: handle automatic backup

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepRateCallback.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepsAdapter.kt, app/src/main/res/layout/activity_sleep.xml, app/src/main/res/layout/layout_sleep_item.xml, doc/README.adoc
It's better to leave the editing functionality to the dedicated sleep
activity.
Fixes <https://github.com/vmiklos/plees-tracker/issues/161>.
Change-Id: Id96ae6d1ec7d9b1dd512899bcbaa5fb246a093e5
=> main activity: make the rating widget read-only

.github/workflows/tests.yml
To see if this helps with the hang that doesn't happen for me locally.
Change-Id: I7048f01f7c1d756aefb4686b7ecff4c0ee21457a
=> CI: update android-emulator-runner to v2.19.0

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt, app/src/main/res/values/strings.xml
It's hard to guess what is the intent when the duration would be
negative (either the new start/stop date is incorrectly provided or you
meant to adjust the other end first), so just refusing the edit with a
clear error is the best.
Fixes <https://github.com/vmiklos/plees-tracker/issues/178>.
Change-Id: I79597b06e2d9e8a14366578771a6bc2850b03125
=> sleep activity: prevent negative sleep durations

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, doc/README.adoc
To avoid duplicates when importing more than once.
Fixes <https://github.com/vmiklos/plees-tracker/issues/207>.
Change-Id: I28da934c4171e9e57cf00c39c67715829c1f1bfe
=> Calendar import: read sleeps incrementally

app/build.gradle, app/src/main/AndroidManifest.xml
https://developer.android.com/guide/topics/manifest/activity-element#exported
is now required for MainActivity/TileService/ToggleWidget, just set all
of these to true for now, assuming that means unchanged behavior.
Change-Id: Ibd21361e8db4562282479adfc0d3887222ae9bcb
=> Update target SDK to Android 12

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
An alternative solution would be to migrate to MaterialCardView which
has a stroke width/color property, but that seems to break e.g. tapping
on the start/stop FAB, so go with an explicit divider.
Fixes <https://github.com/vmiklos/plees-tracker/issues/208>.
Change-Id: Ibb79568ef8b8e74b1ea3ddd9f280e96037fd4263
=> main activity: enable separators between sleep items

.github/workflows/tests.yml
> macOS-latest workflows will use macOS-11 soon. For more details, see https://github.com/actions/virtual-environments/issues/4060
So try to do that upgrade early to see if it works.
Change-Id: I3f0d0274cfd673037226f684d9f7a975ca10cc65
=> CI: build on macos-11

app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityInstrumentedTest.kt, app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainViewModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/Sleep.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepDao.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt
Instead of using a timestamp to make sure no duplicates, I figured it's more robust to just goes through the sleeps and and make sure no duplicates are added based on the start and stop times. It's not the most efficient way, but the data types used are very small and importing/exporting is not done that frequently so it shouldn't really matter.
This fixes calendar importing/exporting duplicates, and also duplicates from importing .csv files.
Also moves calendar importing logic from MainActivity to DataModel since that's where exporting logic is, and seems to fit better.
Related to #150 #207 #209
=> Fix for duplicates on calendar import/export and file import

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/SleepCommentCallback.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepRateCallback.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepViewModel.kt, app/src/main/res/layout/activity_sleep.xml
This requires improving SleepViewModel.updateSleep(), so that there is
no loop between SleepCommentCallback.onTextChanged() and
SleepViewModel.updateSleep().
This was not a problem with the rating and is good enough for now, but
needs revisiting later.
Resolves <https://github.com/vmiklos/plees-tracker/issues/239>.
Change-Id: Ie375ecec35e317b3b5b9d1c7ebd180be87983059
=> Sleep comments: add UI

app/src/main/java/hu/vmiklos/plees_tracker/SleepCommentCallback.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepRateCallback.kt
Just a small patch that fix #253.
However, note that the "main" issue is still unresolved : When showing in the SleepViewModel, a listener (TextWatcher) is registered to the comment field.
Then, it is kept and another watcher is added for each update on the model. That still need to be addressed by unsuscribing  the TextWatcher.
=> [#253] Patch to prevent updates without change

NEWS.adoc, app/build.gradle, app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
Otherwise it's hard to explain the result when you expect 8 hours, but
get 7 or 9 in the DST change case.
Change-Id: Id82812f4bd1df173fae5c9ff6e90ff11d203d682
=> Format timestamp: show timezone

NEWS.adoc, app/src/main/res/layout/activity_sleep.xml
The CSV import/export was already capable of doing this.
Fixes <https://github.com/vmiklos/plees-tracker/issues/277>.
Change-Id: I5157792558d06904498ae57b566596fe63c0f160
=> sleep activity: allow multi-line notes

app/build.gradle, app/src/main/AndroidManifest.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
com.android.tools.build:gradle 7.2.0 says this will be required sooner
or later.
Change-Id: I4e6802924d296bfad5d6bddef4e065a79718aeda
=> Move package from Android manifest to build files

app/src/main/java/hu/vmiklos/plees_tracker/MainService.kt
The pending indent is OK to be immutable, and now it's required to state
that explicitly.
Fixes <https://github.com/vmiklos/plees-tracker/issues/285>.
Change-Id: Ifc4752099d7fbddf58c6c3884b7b6e233093e529
=> main service: fix crash on Android 12

.github/workflows/tests.yml, app/build.gradle, tools/ci-build.sh
If a app/keystore/plees_keystore.jks exists, then sign the release APK
using that. If it's not there, then the behavior is meant to be
unchanged.
Finally do provide such a keystore during the CI build.
Related to <https://github.com/vmiklos/plees-tracker/issues/298>.
Change-Id: I70a08fa74960b15529dc0f7258973a4031415d99
=> CI: optionally sign release APKs

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, doc/README.adoc
Assuming one doesn't fall asleep right after the start, reduce duration
by this fixed amount to have more real stats.
Fixes <https://github.com/vmiklos/plees-tracker/issues/274>.
Change-Id: I5c41419ef6b74431f55d6e161357c850933801ca
=> data model: add a start time offset

NEWS.adoc, app/build.gradle, app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
All you loose is that you don't get timezone in timestamps, which is
just a nice-to-have.
Fixes <https://github.com/vmiklos/plees-tracker/issues/282>.
Change-Id: Ic0ad551843dee916d64b22398ccec906b1ae26bc
=> Lower baseline to API 23 (Android 6.0)

NEWS.adoc, app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, app/src/test/java/hu/vmiklos/plees_tracker/DataModelUnitTest.kt
Hide seconds and timezone, but add a setting to restore them.
These are typically not needed in practice, but they can be useful when
testing or during DST -- those 2 nights every year.
Fixes <https://github.com/vmiklos/plees-tracker/issues/309>.
Change-Id: Ib3921d40725d651b909c0c96d47e360010eeea7f
=> Make the dashboard time format more compact by default

NEWS.adoc, app/src/main/res/drawable/ic_awake_for.xml, app/src/main/res/layout/layout_sleep_item.xml
Fixes <https://github.com/vmiklos/plees-tracker/issues/275>.
Change-Id: If744b6d76a768074144ac4fd6d3d37493938bc25
=> sleep item layout: add dedicated icon for the 'awake for' row

NEWS.adoc, app/build.gradle, app/src/main/AndroidManifest.xml
I.e. fix the app to work with Android 13
See
<https://android.googlesource.com/platform/packages/apps/DeskClock/+/1baadbe248e0bcff32c9eb02483eb503e62eef94%5E%21/>,
the Clock app does the same now.
Change-Id: I921d286e82de52db1177ca45f67991f8942f52b7
=> Update targetSdkVersion to 33

NEWS.md, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml
The doc is hard to discover, so give a brief summary when no sleeps are
shown and point out the relevant menu item.
Resolves <https://github.com/vmiklos/plees-tracker/issues/330>.
Change-Id: I33ff6eea6490762a3345b06568de8c4d9027aa78
=> main activity: add placeholder text when there are no sleeps

app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
These are closing resources, they are meant to be really empty.
Change-Id: I2b834ec319525da210a58609b41fc255f448d1cd
=> DataModel: fix unused variable in empty catch block

app/src/main/AndroidManifest.xml, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, guide/src/news.md
The steps from
<https://github.com/vmiklos/plees-tracker/issues/292#issuecomment-1185306926>
describe that in case the app is already in the foreground, then stop
from the notification drawer won't do anything.
The trouble is that the toggle is implemented as a side-effect of
the creation of the main activity, which is optimized away when the main
activity is already the top of the activity stack. The benefit of this
approach is that once the toggle happens from the main activity, we can
be sure that the DataModel singleton is initialized and also can use the
view model of the activity for coroutine purposes (the stop involves an
async db operation).
Fix the problem by following the advice from
<https://stackoverflow.com/questions/53459111/launch-activity-from-notification-instantiating-ac …
=> Fix lack of toggle from the notification drawer when app is already foreground

app/src/main/java/hu/vmiklos/plees_tracker/ToggleWidget.kt, guide/src/news.md
- Intent.FLAG_ACTIVITY_NEW_TASK was used in the working TileService, but
not in the widget
- PendingIntent.FLAG_IMMUTABLE was used in the working MainService, but
not in the widget
Fixes <https://github.com/vmiklos/plees-tracker/issues/359>.
Change-Id: Ibf58ad6c76aaefe14fbac5b716b30c1f7c04743d
=> Fix toggle widget to work on Android 12

app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
This could happen when the quick setting tile launched the activity,
then rotation re-launched the activity with the same intent parameters,
so the tracking stopped.
As suggested in the issue, just remove the parameter once consumed.
Fixes <https://github.com/vmiklos/plees-tracker/issues/365>.
Change-Id: I9b95959fe10065008492e8aa49f9045400420ea5
=> Don't toggle tracking state on rotation

app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/StatsActivity.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, app/src/test/java/hu/vmiklos/plees_tracker/DataModelUnitTest.kt, guide/src/usage.md
And enable it by default, see the guide for rationale.
Fixes <https://github.com/vmiklos/plees-tracker/issues/366>.
Change-Id: Ie09db97d72eafbdfbe665ce818133d5a0df5ee03
=> Average of daily sums: add a mode to ignore empty days

guide/src/usage.md
It's not the setting that ignores something.
Change-Id: Iaecb0b3f9306459b70fab191f0d56497bcb0dae1
=> guide: improve wording of the 'Ignore empty days when showing average of daily sums' setting

.idea/misc.xml, app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/res/values/strings.xml
It turns out openOutputStream() can throw an exception, which is not
obvious at first, since it returns a nullable output stream, so first I
assumed that it returns a null output stream on failure.
Also, given that it was assumed export can't reach showing a toast on
failure, we always presented success. Fix this and report an error on
failure.
Fixes <https://github.com/vmiklos/plees-tracker/issues/406>.
Change-Id: Ic5922e4b38f544debe0888bd636d21be8fe35f49
=> Export to file: avoid reporting success in toast on failure

app/src/main/java/hu/vmiklos/plees_tracker/GraphsActivity.kt, app/src/main/res/menu/menu_graphs.xml, app/src/main/res/values/strings.xml, app/src/test/java/hu/vmiklos/plees_tracker/GraphsActivityUnitTest.kt, guide/src/usage.md
Adds variance and standard deviation graph. Graphs are cumulative – the variance for the day x_k is calculated from data from days x_1 to x_k.
Closes https://github.com/vmiklos/plees-tracker/issues/388
(This is what 16h sleep does with your stats)
=> feat: Variance and standard deviation graph

app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, guide/src/hacking.md
Import from file is normally a non-blocking operation, so it can be done
on the UI, except when going via the storage access framework, e.g. when
the file is provided by nextcloud. This resulted in a crash like:
2023-10-13 22:10:48.342  7896-7896  AndroidRuntime          hu.vmiklos.plees_tracker.debug       E  FATAL EXCEPTION: main
at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:814)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2043)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1858)
at android.content.ContentResolver.openInputStream(ContentResolver.java:1528)
at …
=> import file: handle when the storage is in fact a network one

app/src/main/AndroidManifest.xml
This will be required on android 14, see
<https://developer.android.com/about/versions/14/changes/fgs-types-required>.
Change-Id: Ia25f02fb0a6c70c7d42458b79e5a5034bf5094fc
=> notification service: add foreground service type

app/src/main/java/hu/vmiklos/plees_tracker/GraphsActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/SleepActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/StatsActivity.kt, guide/src/news.md
Pressing the back button on the action bar of these 3 activities
resulted in no action.
At some point in the past, just calling setDisplayHomeAsUpEnabled(true)
was enough, but looks like these days nothing happens by default.
Fix the problem by explicitly handling android.R.id.home and there
finishing the current activity.
=> Fix no action on pressing the back button on the action bar

app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Starting with TargetSDK 33, Launchers can call for an app's monochrome icon variant to create a themed version from a color palette based on the wallpaper or the user's preference.
=> Added Themed / Monochrome Launcher icon support for devices that support it

.idea/deploymentTargetDropDown.xml, app/src/main/AndroidManifest.xml, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/Preferences.kt, app/src/main/java/hu/vmiklos/plees_tracker/PreferencesActivity.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, guide/src/usage.md
This pull request adds these following changes to the app:
- Do not disturb integration, when the user starts tracking their sleep the app turns DND mode automatically and turns it to the last state the user left DND on when they stop tracking sleep
- Added DND setting to the preferences, it also asks the user for the DND permission which is required for DND integration to work.
This might not be the perfect way to do this but it does seem to work well for me at least (on emulator and real phone), and this pull request also solves issue #419
=> Add DND (Do Not Disturb) Integration

.github/workflows/tests.yml, app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityInstrumentedTest.kt
Meant to fix this warning:
"Node.js 16 actions are deprecated. Please update the following actions
to use Node.js 20: actions/checkout@v2, actions/setup-java@v1,
reactivecircus/android-emulator-runner@v2.27.0. For more information
see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."
=> CI: update actions

app/src/main/java/hu/vmiklos/plees_tracker/Sleep.kt, app/src/test/java/hu/vmiklos/plees_tracker/SleepUnitTest.kt
This is called from areContentsTheSame() in SleepsAdapter.kt.
Fixes <https://github.com/vmiklos/plees-tracker/issues/455>.
=> main activity: fix missing update after changing the rating of a sleep

app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityInstrumentedTest.kt, app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
Return the usual formatted string instead of an empty one.
Fixes <https://github.com/vmiklos/plees-tracker/issues/436>.
=> Show zero time instead of empty text without sleeps

app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt
Have the getAfterLive() and the liveDataBoolean("use_median", ...) calls
in separate scopes, so in case we want to add more settings there in the
future, then no need to increase nesting again this way.
And in case afterSleep is not a callable, then it would be only called
once, so the chained LiveData wouldn't update properly.
Fixes <https://github.com/vmiklos/plees-tracker/issues/474>.
=> Don't require app restart when changing the `use_median` setting

app/build.gradle, app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityInstrumentedTest.kt, app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityUITest.kt
Try the uiautomator approach, espresso doesn't seem to be able to cope
with the coroutines/room/observer-based UI updates.
=> test: resolve FIXME in sleep create test

.github/workflows/tests.yml, tools/ci-build.sh
See <https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/>.
=> CI: migrate away from old macOS

tools/ci-build.sh
The root of the problem was not quoting the arg of "echo" when writing
the base64 of the .jks, but by the time I figured this out, I lost the
old value of the KEYSTORE secret, so re-generate all 4 and try to
re-enable this.
=> CI: restore taking key store settings from secrets

app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityUITest.kt, app/src/androidTest/java/hu/vmiklos/plees_tracker/SleepActivityUITest.kt, app/src/androidTest/java/hu/vmiklos/plees_tracker/UITestBase.kt
This is used only during setup, not part of the actual "when" action of
the UI tests. Also means that testUpdate() can now set the start of the
sleep only once, since the original start/stop value can be controlled.
=> test: avoid going via the UI in createSleep()

app/src/androidTest/java/hu/vmiklos/plees_tracker/MainActivityUITest.kt, app/src/androidTest/java/hu/vmiklos/plees_tracker/UITestBase.kt
Best to always do the "wait for text + assert" in one go, and it's less
code this way.
=> test: clean up getResText() with its hint argument

app/src/androidTest/java/hu/vmiklos/plees_tracker/UITestBase.kt
Leftover from the extract of this class from MainActivityUITest, where
everything was protected by default as a start.
=> UITestBase: pkg can be private

app/src/main/res/values-night/colors.xml
While "Sleeps" and "Daily" have very similar [HSL](https://en.wikipedia.org/wiki/HSL_and_HSV) lightness values, "Daily" looks darker on my devices. There must be a difference in the perceived brightness of the two colors. This PR modifies the color of "Daily" to make it more visually consistent with "Sleeps".
Here is a preview. Top has the old color; bottom has the new color.
P.S.: Thanks again for the updated dark mode. It has made Plees Tracker more pleasant to use.
=> Dark mode: Slightly adjust Daily color

app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, guide/src/usage.md
End-users sometimes want to show their sleep log to other people, but
the data exported to a file, but that is not human-readable.
The default export format is a CSV that is meant to be easy to import
back, i.e. a machine-readable file format.
Fix the problem by adding a setting (defaults to false): if enabled, the
export result will have formatted timestamps and also the sleep length
will be written there, if if that's redundant for a machine reader.
Fixes <https://github.com/vmiklos/plees-tracker/issues/515>.
=> Export to file: add a pretty CSV mode

app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
With the old plees-tracker.csv, the next export created 'plees-tracker
(1).csv' and so on; try to avoid annoying spaces in filenames by adding
the date to the name, so if you sleep once a day (typical), then you
don't hit this.
Fixes <https://github.com/vmiklos/plees-tracker/issues/527>.
=> Export to file: include ISO date in default file name

app/src/main/java/hu/vmiklos/plees_tracker/DataModel.kt, app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt
Mostly because this way the strings can be exposed in the preferences
activity later.
Note that there is no explicit
```
editor.remove("bedtime_hour")
editor.remove("bedtime_minute")
editor.remove("wakeup_hour")
editor.remove("wakeup_minute")
```
because these settings were never in a released version.
=> bedtime/wakeup: merge into just 2 settings

app/build.gradle, app/src/main/java/hu/vmiklos/plees_tracker/Preferences.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Towards eliminating the inconsistency that these reminders can be set
via a menu item, while everything else is in the preferences activity.
This just shows the preferences so far, no modification is possible yet.
=> bedtime/wakeup: show the value of these in the preferences activity

app/src/main/java/hu/vmiklos/plees_tracker/MainActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/PreferencesActivity.kt, app/src/main/java/hu/vmiklos/plees_tracker/SharedPreferencesChangeListener.kt, app/src/main/res/menu/menu_main.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, guide/src/news.md
And add a SwitchPreference to enable or disable this, which means it's
possible to disable this -- this was missing previously.
=> bedtime and wakeup reminders: move UI to the preferences activity
